# Generated by Django 5.0.6 on 2024-07-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_click',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
